# Generated by Django 2.2.6 on 2019-10-27 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='N/A', max_length=100)),
                ('last_name', models.CharField(default='N/A', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='N/A', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(default='N/A', max_length=100)),
                ('address_line_2', models.CharField(default='N/A', max_length=100)),
                ('city_town', models.CharField(default='N/A', max_length=100)),
                ('county', models.CharField(default='N/A', max_length=100)),
                ('post_code', models.CharField(default='N/A', max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('location', models.CharField(default='N/A', max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propmanager.Owner')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propmanager.PropertyType')),
            ],
        ),
    ]
